### ISSUE TITLE
ERROR 503: Service Temporarily Unavailable.

### ISSUE THREAD

**Issue by Lik3Hackdev** [cryinkfly/Fusion-360---Linux-Wine-Version-#100]
There is a issue with downloading the archives .
I think the links in the bash script were expired or does not exist.
Please update these. If it is not the problem _please look up on this as fast as possible because I was  believing on these projects to make my cad models_ 

This Problem also bugs the **Solidworks installer**
[installer-log.txt](https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/files/7192545/installer-log.txt)

**Comment by cryinkfly** [comment]
@Lik3Hackdev Thank you very much for this information, but I have looked into your log file and found out that this problem is a temporary issue with no connection to the server for downloading the winetricks packages! ⚠️ 

This issue can sometimes exist when server is down for working or a update and so you must wait for it. ⚙️

Please test the installation later. 😊

… and I testing this tomorrow on my Systems. ✅

**Comment by cryinkfly** [comment]
### So, I have checked the connections to servers and it works! :+1: 

![Bildschirmfoto_2021-09-20_11-18-20](https://user-images.githubusercontent.com/79079633/133980666-f0c83b24-f6b0-4314-8936-c729be795be5.png)

![Bildschirmfoto_2021-09-20_11-18-49](https://user-images.githubusercontent.com/79079633/133980700-4176fa13-cb85-4d4f-8f23-d68502f3892b.png)

**Comment by Lik3Hackdev** [comment]
Yes I think you are right today I reran the script and all worked fine It installed successfully. The servers would have been down when I was running the script.
