### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by se3d** [cryinkfly/Fusion-360---Linux-Wine-Version-#106]
There are a lot of erros on Linux Mint LDME4  (based on debian 10).

[...]
Hit:1 http://security.debian.org buster/updates InRelease                                                                                                               
Hit:2 http://dl.google.com/linux/chrome/deb stable InRelease                                                                                                            
Hit:3 https://deb.opera.com/opera-stable stable InRelease                                                                                                               
Ign:4 http://mint-packages.c3sl.ufpr.br debbie InRelease                                                                                                                
Hit:5 https://deb.debian.org/debian buster InRelease                                                                                       
Hit:6 https://deb.debian.org/debian buster-updates InRelease                              
Get:7 http://linuxcnc.org buster InRelease [28.5 kB]                                      
Hit:8 http://mint-packages.c3sl.ufpr.br debbie Release                                                
Hit:9 https://deb.debian.org/debian buster-backports InRelease                                        
Get:10 https://dl.cloudsmith.io/public/balena/etcher/deb/linuxmint debbie InRelease [5057 B]
**Err:7 http://linuxcnc.org buster InRelease                                                                                                                              
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3CB9FD148F374FEF**
Reading package lists... Done
W: GPG error: http://linuxcnc.org buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3CB9FD148F374FEF
**E: The repository 'http://linuxcnc.org buster InRelease' is not signed.**
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by cryinkfly** [comment]
This error what you get is your configured repository:

> Err:7 http://linuxcnc.org buster InRelease
The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3CB9FD148F374FEF
Reading package lists... Done
W: GPG error: http://linuxcnc.org buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3CB9FD148F374FEF
E: The repository 'http://linuxcnc.org buster InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

You must delete this or change! 😊
