### ISSUE TITLE
Force Closes: Offline AND Online Error

### ISSUE THREAD

**Issue by changetotower** [cryinkfly/Fusion-360---Linux-Wine-Version-#2]
Hello. Many thanks for this workaround, highly appreciated. So far I got Fusion 360 opening, but it closes again with the initial error message that it cannot work offline (something like no data or storage available, although my 256GB disk is almost completely free) and it will try to connect to the internet. Thereafter I get the error that it could not connect to the internet either and the application closes. Using latest Pop!_OS. Thank you!

**Comment by cryinkfly** [comment]
Hello. :)

Can you explain to me exactly what are doing to run this program on your system snd it will be maybe good for me, when you can make a screenshot of it?

LG Steve

**Comment by pastatopf** [comment]
Hi,

I had the same issue.
I followed your list up to point 15. I was able to give my login credentials to fusion 360. But then afterwards I got this 'Fusion 360' Error message (it is in german, but I think this is no problem for you? :-)):
Fusion konnte leider nicht genügend Daten für den Offline-Modus speichern und benötigt eine Internetverbindung. Stellen Sie zum Fortfahren sicher, dass Sie über eine funktionierende Internetverbindung verfügen'.

I checked my network and everything is fine (otherwise I would not be able to write this post in Github :-))

Do you have any idea, what the problem is?

BR

**Comment by cryinkfly** [comment]
Can you check, if you have installed these packages:

libc.so.6()(64bit)
libc.so.6(GLIBC_2.2.5)(64bit)
libc.so.6(GLIBC_2.4)(64bit)
libc.so.6(GLIBC_2.3.4)(64bit)
libc.so.6(GLIBC_2.14)(64bit)
libpthread.so.0()(64bit)
libc.so.6(GLIBC_2.3)(64bit)
libpthread.so.0(GLIBC_2.2.5)(64bit)
libm.so.6()(64bit)
libc.so.6(GLIBC_2.7)(64bit)
libm.so.6(GLIBC_2.2.5)(64bit)
libglib-2.0.so.0()(64bit)
libgobject-2.0.so.0()(64bit)
libX11.so.6()(64bit)
libgcc_s.so.1()(64bit)
libdl.so.2()(64bit)
libgcc_s.so.1(GCC_3.0)(64bit)
libdl.so.2(GLIBC_2.2.5)(64bit)
libz.so.1()(64bit)
libc.so.6(GLIBC_2.17)(64bit)
libpthread.so.0(GLIBC_2.3.2)(64bit)
libc.so.6(GLIBC_2.3.2)(64bit)
libxml2.so.2()(64bit)
libXext.so.6()(64bit)
libxml2.so.2(LIBXML2_2.4.30)(64bit)
libc.so.6(GLIBC_2.6)(64bit)
libdbus-1.so.3()(64bit)
libgstreamer-1.0.so.0()(64bit)
libc.so.6(GLIBC_2.9)(64bit)
libxml2.so.2(LIBXML2_2.6.0)(64bit)
libc.so.6(GLIBC_2.10)(64bit)
libc.so.6(GLIBC_2.16)(64bit)
libjpeg.so.8()(64bit)
libfreetype.so.6()(64bit)
libudev.so.1()(64bit)
libudev.so.1(LIBUDEV_183)(64bit)
libfontconfig.so.1()(64bit)
libpng16.so.16()(64bit)
libXrender.so.1()(64bit)
libgnutls.so.30()(64bit)
libasound.so.2()(64bit)
libasound.so.2(ALSA_0.9)(64bit)
libpulse.so.0()(64bit)
libpulse.so.0(PULSE_0)(64bit)
libgssapi_krb5.so.2()(64bit)
liblcms2.so.2()(64bit)
libXfixes.so.3()(64bit)
libcups.so.2()(64bit)
libldap_r-2.4.so.2()(64bit)
libasound.so.2(ALSA_0.9.0rc4)(64bit)
libgstvideo-1.0.so.0()(64bit)
libGL.so.1()(64bit)
libresolv.so.2()(64bit)
libresolv.so.2(GLIBC_2.2.5)(64bit)
libtiff.so.5()(64bit)
libXrandr.so.2()(64bit)
libkrb5.so.3()(64bit)
liblber-2.4.so.2()(64bit)
libXi.so.6()(64bit)
libXinerama.so.1()(64bit)
libgstaudio-1.0.so.0()(64bit)
libXcomposite.so.1()(64bit)
libncurses.so.6()(64bit)
libXcursor.so.1()(64bit)
libv4l2.so.0()(64bit)
libxml2.so.2(LIBXML2_2.9.0)(64bit)
libxslt.so.1()(64bit)
libSDL2-2.0.so.0()(64bit)
libm.so.6(GLIBC_2.23)(64bit)
libxml2.so.2(LIBXML2_2.7.3)(64bit)
libXxf86vm.so.1()(64bit)
libgsm.so.1()(64bit)
libxml2.so.2(LIBXML2_2.5.7)(64bit)
libxml2.so.2(LIBXML2_2.5.8)(64bit)
samba-winbind
libgphoto2.so.6()(64bit)
libgphoto2_port.so.12()(64bit)
libgphoto2_port.so.12(LIBGPHOTO2_5_0)(64bit)
libmpg123.so.0()(64bit)
libopenal.so.1()(64bit)
libpthread.so.0(GLIBC_2.4)(64bit)
libxml2.so.2(LIBXML2_2.6.15)(64bit)
libsane.so.1()(64bit)
libunwind.so.8()(64bit)
libxml2.so.2(LIBXML2_2.6.14)(64bit)
libxml2.so.2(LIBXML2_2.6.21)(64bit)
libxml2.so.2(LIBXML2_2.6.8)(64bit)
libpcap.so.1()(64bit)
libvulkan.so.1()(64bit)
libxml2.so.2(LIBXML2_2.6.2)(64bit)
libxml2.so.2(LIBXML2_2.6.23)(64bit)
libFAudio.so.0()(64bit)
libGLU.so.1()(64bit)
libOSMesa.so.8()(64bit)
libcapi20.so.3()(64bit)
libwine.so.1()(64bit)
libwine.so.1(WINE_1.0)(64bit)

... and can you also install these packages:

libopenssl1_0_0
libGLU

Give me a report, please. :-)

**Comment by pastatopf** [comment]
So far it seems that I have all of this libraries installed. But still getting the same error.

I noticed, that I can't ping anything, while being in the windows shell (see below). Can you try it from your side and tell me if you are able to ping google.com for example?

`osantiag@osantiag-power-linux:/etc/network$ ping google.com
PING google.com (216.58.212.142) 56(84) bytes of data.
64 bytes from fra16s46-in-f14.1e100.net (216.58.212.142): icmp_seq=1 ttl=117 time=27.0 ms
64 bytes from fra16s46-in-f14.1e100.net (216.58.212.142): icmp_seq=2 ttl=117 time=25.2 ms
64 bytes from fra16s46-in-f14.1e100.net (216.58.212.142): icmp_seq=3 ttl=117 time=26.0 ms
^C
--- google.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 25.180/26.054/27.021/0.754 ms
osantiag@osantiag-power-linux:/etc/network$ wine cmd
Microsoft Windows 6.2.9200

Z:\etc\network>ping google.com
Pinging google.com [216.58.212.142] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
`

**Comment by cryinkfly** [comment]
Hey @pastatopf 😊,
I have tested this with my configuration and it works for me, when I ping maybe to google.com.

But I search at the moment for a solution. 😊

**Comment by pastatopf** [comment]
Ok, so seems that we are on a good way. :-)

Can you copy paste the ping command and output here please, like I did in my post?

**Comment by cryinkfly** [comment]
@pastatopf I have founded a solution, what can solved maybe also you problem. I have installed different linux distribution and some of these have doesn’t set correctly the hostname and the computer-name, but this is important for some applications when they run with wine. And on my production system I have configured this, because this is was important for me to get Flatpak apps to run on my system. 😅

Check this out, please. 😊

You must edit these two files with root privileges:

/etc/hosts and /etc/hostname 

You must add a new line into /etc/hosts like this for a example:

127.0.1.1      computer-name

... then you safe this file and add only the „computer-name“ to the /etc/hostname . 😊


![24695125-505D-4736-A091-F8C061922282](https://user-images.githubusercontent.com/79079633/113913737-f3929000-97dc-11eb-9434-621b2efefc04.jpeg)


![C3B7EB20-5AA2-4142-AAD0-6984D85F2139](https://user-images.githubusercontent.com/79079633/113913711-eecddc00-97dc-11eb-956f-9561f032317b.jpeg)

**Comment by pastatopf** [comment]
@cryinkfly : I already have that in the mentioned files. This is how they look like on my computer. Do you think there is something missing?

`osantiag@osantiag-power-linux:~$ cat /etc/hosts
127.0.0.1	localhost
127.0.1.1	osantiag-power-linux

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
# BEGIN ANSIBLE MANAGED BLOCK
x.x.x.x tool-server
x.x.x.x k8s-server
# END ANSIBLE MANAGED BLOCK
osantiag@osantiag-power-linux:~$ cat /etc/hostname
osantiag-power-linux
osantiag@osantiag-power-linux:~$ `

**Comment by cryinkfly** [comment]
@pastatopf Which linux distribution and wine version did you use? 😊

**Comment by pastatopf** [comment]
Linux Distribution: Ubuntu 20.04.2 LTS
wine-5.0 (Ubuntu 5.0-3ubuntu1)

**Comment by cryinkfly** [comment]
Okay I check this in the next time. 😊👍🏻

**Comment by cryinkfly** [comment]
Hi @pastatopf ,

I've already founded a few problems on Ubuntu. The first one is, that the wine version 5.0-3ubuntu1 have a problem to connect to the internet! So it's better when you change to another wine version that is older than this one.


![Bildschirmfoto vom 2021-04-08 08-05-17](https://user-images.githubusercontent.com/79079633/114002792-7b1fe380-985d-11eb-83ea-564a03ccff8e.png)
![Bildschirmfoto vom 2021-04-08 11-29-07](https://user-images.githubusercontent.com/79079633/114003423-04cfb100-985e-11eb-9718-3813ab78e504.png)

... and the next problem is, that wine need for this program the package "winbind" and this package is also installed on my system with openSUSE Leap 15.2.


![Bildschirmfoto vom 2021-04-08 08-52-41](https://user-images.githubusercontent.com/79079633/114003007-b28e9000-985d-11eb-8f66-8173562d13bb.png)
![Bildschirmfoto vom 2021-04-08 08-54-32](https://user-images.githubusercontent.com/79079633/114003136-ca661400-985d-11eb-8da1-7519a39d499b.png)

So, but the problem is still there! ;-) 

![Bildschirmfoto vom 2021-04-08 09-33-01](https://user-images.githubusercontent.com/79079633/114003315-eff31d80-985d-11eb-8cda-f703e8738295.png)
![Bildschirmfoto vom 2021-04-08 10-23-43](https://user-images.githubusercontent.com/79079633/114003319-f1244a80-985d-11eb-8131-251be697eca8.png)
![Bildschirmfoto vom 2021-04-08 10-26-50](https://user-images.githubusercontent.com/79079633/114003323-f1bce100-985d-11eb-887a-614a475d0679.png)
![Bildschirmfoto vom 2021-04-08 10-27-30](https://user-images.githubusercontent.com/79079633/114003329-f2557780-985d-11eb-8f6b-12f1de56a0c7.png)

... but I keep testing. :-)

**Comment by cryinkfly** [comment]
@pastatopf Fusion 360 works also on Ubuntu 20.04.2: https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/commit/c415bbc10f674a598b9393bfa0afb157a3ef92a9

Good luck :)

**Comment by pastatopf** [comment]
@cryinkfly : Great News! Good work!

I tried it following your video, but still getting an error while starting. Which wine version did you use?

BR

**Comment by cryinkfly** [comment]
I have installed the wine version 6.5 (staging), but you must select later thewine Version lutris.5.0... as your runner. 😊

**Comment by pastatopf** [comment]
Oh sure, you are right. Lutris uses its own runner and not the one installed on my linux, right?

The issue is driving me crazy.
Possibly you are interested in a meeting via zoom to fix the issue with me together in a screen sharing session? Would that be ok for you?

**Comment by cryinkfly** [comment]
😅 yes, Lutris have there own runners, what we can select to run a program without our basis wine version that is installed on our system. 

... we can make this, but my english is not so good. 😅

I create a account for this now.

**Comment by pastatopf** [comment]
Kein Problem, mein Deutsch ist auch besser als mein Englisch. :-)

Über Zoom? Siehtst du meine Emailadresse in Github?

**Comment by cryinkfly** [comment]
😅 Nein.. ich sehe sie leider nicht.

**Comment by pastatopf** [comment]
Du solltest jetzt eine Mail von mir haben.

**Comment by cryinkfly** [comment]
I habe dir eine Anfrage geschickt. 👍🏻

**Comment by pastatopf** [comment]
Hm, leider noch nichts angekommen. Ich hab dir auch mal eine Anfrage geschickt.

**Comment by cryinkfly** [comment]
@pastatopf Ich hoffe, dass ich dir bei deinem Problem weiterhelfen konnte 😅

**Comment by pastatopf** [comment]
It is working now on my system. 
Thanks to @cryinkfly for your great support. Finally following your last [youtube tutorial](https://www.youtube.com/watch?v=R-ev3dhNM98&t=7s) worked for me.

Additionally I wrote the attached script to execute the steps described by @cryinkfly. I attach it to this post, this makes the installation steps more reproducable.

`cd ~

sudo apt-get update 
sudo apt-get upgrade -y

sudo dpkg --add-architecture i386  
wget -nc https://dl.winehq.org/wine-builds/winehq.key 
sudo apt-key add winehq.key 
sudo add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main' 
sudo add-apt-repository ppa:lutris-team/lutris 
sudo apt update 
sudo apt install winehq-staging winetricks lutris p7zip p7zip-full p7zip-rar curl winbind -y

winetricks corefonts vcrun2017 msxml4 dxvk

winecfg 
cd ~/Downloads 
mkdir fusion360 
cd fusion360

wget https://dl.appstreaming.autodesk.com/production/installers/Fusion%20360%20Admin%20Install.exe
7z x -osetup/ "Fusion 360 Admin Install.exe" 
curl -Lo setup/platform.py github.com/python/cpython/raw/3.5/Lib/platform.py 
sed -i 's/winver._platform_version or //' setup/platform.py

wine setup/streamer.exe -p deploy -g -f log.txt --quiet
wine setup/streamer.exe -p deploy -g -f log.txt --quiet

cd $HOME && mkdir .Fusion360 && cd .Fusion360

#env WINEPREFIX="$HOME/.wine" wine C:\\windows\\command\\start.exe /Unix $HOME/.wine/dosdevices/c:/ProgramData/Microsoft/Windows/Start\ Menu/Programs/Autodesk/Autodesk\ Fusion\ 360.lnk 
`

**Comment by cryinkfly** [comment]
@pastatopf I am glad that it's now working for you too.
