### ISSUE TITLE
Create a Flatpak App for Fusion 360

### ISSUE THREAD

**Issue by cryinkfly** [cryinkfly/Fusion-360---Linux-Wine-Version-#5]
# Create a Flatpak App for Fusion 360

### Is there anyone here to, who can help me by creating a Flatpak App of Fusion 360 for Linux?
When you have some ideas and suggestions, then You can share this with me here.

![Flatpak_Fusion360](https://user-images.githubusercontent.com/79079633/114560377-ee19c780-9c6c-11eb-97e1-44c70b5ac65d.png)

**Comment by dreamcat4** [comment]
+1000

i think a container image is an excellent idea. the choice for flatpak is my preffered too, it seems best. however if that is too difficult then trying to make an appimage might be simpler process. just thing is appimage is not so good

either way it is a great idea, and really hope we can get some more people interested in this approach

another open question is how to permit fusion 360 update itself inside of the container. because that is not normally permitted. so we have to allow that. if it cannot update itself somehow... then we need to rely on somebody to keep remaking new images (and also for testing them)

however the main goal is obviously to bundle together and freeze the correct wine versions, enviroments etc. and needed configurations. so that it just launches all together. and with fewer manual steps to complete

finally another issue is about the licensing of necessary dependancies. because unfortunately since it depends on specific microsoft runtime libraries. for the .NET frameworks etc. and also for the web connections / web browser side

this then creates extra barriers and makes it harder to redistribute. but what we could do instead it distribute a 'build script'. to locally build the container image from scratch. and then the build script itself is a free software

but also interrupting the build script may be installer screens. that open up, and require to clock 'ok' and 'next page' etc. which is ok, but we do need to be able to have them install into the container build environment. (instead of on the host linux / global host system enviroment)

**Comment by cryinkfly** [comment]
@dreamcat4 

> we need to rely on somebody to keep remaking new images (and also for testing them)

That’s not a problem for me 😅 ... but you are right with this problem:

> finally another issue is about the licensing of necessary dependancies. because unfortunately since it depends on specific microsoft runtime libraries. for the .NET frameworks etc.

... and so I think 🤔 ... it will be good maybe, when we create only a basis for Fusion 360 where is wine configured and the 

> 'build script'

... make the rest with the interaction by the user. 👍🏻

**Comment by cryinkfly** [comment]
## Good news!!!

I solved the installation of Fusion 360 into a Flatpak App, but I must configuring some files. 😊👍🏻

**Comment by cryinkfly** [comment]
Here can your read more about one of my way's to get Fusion 360 to run with Flatpak: https://github.com/PhoenicisOrg/phoenicis/issues/2389

**Comment by dreamcat4** [comment]
Great @cryinkfly i do hope the flatpak will be possible. Thanks I shall read the link here.

In the meantime I have pushed some new changes for instructions on my fork you can see here. For the way how I do headless install on regular ubuntu (no flatpak), is just copy-paste all the commands in 1 step. All into an open linux terminal window. Then leave it to complete. And it pops up the login screen. Thanks so much for doing the hard part already, before!

https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/compare/main...dreamcat4:pr-reduce-interactive-steps

It is mostly the same steps as your did before. Just tweaked slightly. And reformatted to be friendly to copy-paste easy mode.

Only edited the **ubuntu / mint** instructions in the README.md. To make the commands less interactive. And more headless. It still might still need X-DISPLAY xserver running IDK.

The biggest improvement was the `winetricks -q` flag for silent headless installs of Dot .NET dependancy etc. Then it no more brings up GUI installer.

That is all from me. Done for the whole weekend for this... I do not plan to make any more suggestions of changes anymore. Except maybe for to raise a bug elsewhere to autodesk ppl. I leave to you to it.

Looking forwards to seeing maybe if we can have flatpak in future. No hurry. Just very glad it works much better now!

Actually I do not use fusion 360 very much. Except to open 3d printer files, from other people. My graphics card is just way too slow (gt 1030). Maybe I can get a faster GPU, at end of this year. Long time from now.

However I shall come back & let you know if anything else of interest, either for fusion. Or maybe if I have any success for running other 3d CAD programs like alibre or rhino. Also for WINE cad stuff. Many thanks

**Comment by cryinkfly** [comment]
@dreamcat4 
### Thank you so much for your help!!! :-)

> That is all from me. Done for the whole weekend for this... I do not plan to make any more suggestions of changes anymore. Except maybe for to raise a bug elsewhere to autodesk ppl. I leave to you to it.

It just takes a lot of time and so I know what you mean. ;-)

> Actually I do not use fusion 360 very much. Except to open 3d printer files, from other people. My graphics card is just way too slow (gt 1030). Maybe I can get a faster GPU, at end of this year. Long time from now.

At the moment it could be difficult to get graphics cards (Corona, etc.), but I search also for new hardware. ;D

---

So I have added one of my way's to running Fusion 360 with Flatpak, but it dosn't work at the moment. ;-)
I have also added your instruction:

![dreamcat4_help](https://user-images.githubusercontent.com/79079633/115914355-204bd600-a472-11eb-9c0b-9e9a69e4a7be.png)

**Comment by plata** [comment]
You might want to take a look at:
https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/issues/6
https://github.com/plata/phoenicis-app-flatpak-generator

**Comment by cryinkfly** [comment]
@plata Ok. Thanks. :-)

**Comment by cryinkfly** [comment]
Autodesk Fusion 360 works now into a Flatpak-Runtime: https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/releases/tag/v2.2

**Comment by destinatorM** [comment]
Is the flatpak-project still in developing or dead?

**Comment by kvngvikram** [comment]
Sorry, I am lost, how exactly can I install the flatpak version ?

**Comment by alextrical** [comment]
I'm also interested in getting this to work in a Flatpak based version of wine, how can I help? I have been trying to get this working myself and would love to help with this project

**Comment by jan-tdy** [comment]
me too
