### ISSUE TITLE
Manjaro Install

### ISSUE THREAD

**Issue by mike-lloyd03** [cryinkfly/Fusion-360---Linux-Wine-Version-#6]
Thank you so much for the work you've put into making this happen. I just ran through your install instructions and it works! I was able to get Fusion 360 up and running and I opened a model for some testing.

The graphics were very distracting with a flash every time I clicked in the 3D space. I opened a sketch and started clicking around and found the same problems. Overall, everything is a bit sluggish as well. For now, my current KVM solution is a bit faster and smoother.

I saw that you referenced an article from Proton. Is is possible to use Proton to run Fusion 360? Being that it was developed for high FPS gaming, I imagine Proton might work well for a 3D CAD program.

**Comment by dreamcat4** [comment]
> The graphics were very distracting with a flash every time I clicked in the 3D space

hello. i am investigating this bug. to try and find out what is the reason behind that. it might take a few more days

**Comment by DragonHunter274** [comment]
Did you disable dxvk after switching to opengl? For me that fixed the flashing issue
(also on arch linux)

**Comment by cryinkfly** [comment]
@mike-lloyd03 

> For now, my current KVM solution is a bit faster and smoother.

when you have installed maybe a Nvidia graphics card on your system, then it’s a good option for you to install the CUDA libraries. 👌🏻

> Did you disable dxvk after switching to opengl? 

If you have configured this?

> Is is possible to use Proton to run Fusion 360? 

I testing a Proton version that works into a Flatpak-Runtime, but this doesn’t work at the moment correctly. ⚙️

... But at the moment I testing a way to change the memory query of wine, because this is important for the simulation workspace! Then when I solved this problem, so you can also calculating a study with your computer (local), but this option doesn’t work at the moment. 😅

**Comment by dreamcat4** [comment]
FYI you might find proton is bad idea for this application. Certainly it didn't work for myself

another thing i noticed (for my 2gb gt1030)... with limited GPU / video ram... when i maximize the workspace to 4k it crashed. Or maybe i just ran out of memory. But i should be upgrading my RAM soon to 64gb. If i can remember next time rebooting the machine

**Comment by mike-lloyd03** [comment]
I followed the guide and set the following:

```
d3d10core = disabled
d3d11 = native
d3d9 = builtin
dxgi = native
```

How do I disable `dxvk`?

**Comment by cryinkfly** [comment]
> But i should be upgrading my RAM soon to 64gb

... and I must change my system in the future. 😅

**Comment by cryinkfly** [comment]
@mike-lloyd03 Have you also change the graphics driver to OpenGL in Fusion 360? 😊

**Comment by mike-lloyd03** [comment]
> @mike-lloyd03 Have you also change the graphics driver to OpenGL in Fusion 360? blush

Yes, I did. I also just noticed this funny little feature:

When I switch desktops, menus in the 3D space appear on every desktop!
![image](https://user-images.githubusercontent.com/49411532/115059873-028fd700-9e9c-11eb-8d71-37b8a9e299b3.png)

**Comment by cryinkfly** [comment]
@mike-lloyd03 This is normally at the moment, but I search for solution. 👍🏻

**Comment by mike-lloyd03** [comment]
@cryinkfly Sounds good! I'm so thankful there's someone working on making this a reality! Much appreciated!

**Comment by mike-lloyd03** [comment]
> Did you disable dxvk after switching to opengl? For me that fixed the flashing issue
> (also on arch linux)

Can you tell me how to do this? I don't see dxvk in my winecfg libraries.

**Comment by cryinkfly** [comment]
@mike-lloyd03 

You must deactivate d3d11, d3d10, d3d9 and dxgi.

**Comment by mike-lloyd03** [comment]
So setting this as per your directions is incorrect?

```
d3d10core = disabled
d3d11 = native
d3d9 = builtin
dxgi = native
```

**Comment by cryinkfly** [comment]
@mike-lloyd03 I was wrong. it doesn't work without these library settings. 😅🤦🏼‍♂️

**Comment by dreamcat4** [comment]
i have that problem too.... but that isnt the same problem as the background (or splash screen) flashing and glitching out whenever you click on a model object

those are 2 different issue

**Comment by cryinkfly** [comment]
@dreamcat4 
> but that isnt the same problem

Can show me this with a picture, please? :-)

**Comment by mike-lloyd03** [comment]
@dreamcat4 I have this same problem. Let me see if I can make a video of it.

**Comment by dreamcat4** [comment]
screenshots

https://www.dropbox.com/sh/fsnyv6a9nubse5u/AAAinp8-NIIx8ObCi-KGLszoa?dl=0

**Comment by mike-lloyd03** [comment]
I tried to capture a video of it but basically, the screen is flashing either to black or to the Fusion360 logo on a white background. Frame rate is normally faster, just slow because of the gif.

![Peek 2021-04-16 11-47](https://user-images.githubusercontent.com/49411532/115070348-afbd1c00-9ea9-11eb-8aa6-a3b0f53a5a1c.gif)

**Comment by cryinkfly** [comment]
@mike-lloyd03  Okay ;-)  I don't have this problem with Fusion 360 on my system.

**Comment by mike-lloyd03** [comment]
Yes you're looks to be working MUCH better than mine. It looks like @dreamcat4 and I are experiencing the same issue and we're both on Arch systems.

@dreamcat4 What desktop environment are you using?

**Comment by dreamcat4** [comment]
ubuntu 20.04, actually just give me a few days and i might be able to narrow it down a bit

**Comment by mike-lloyd03** [comment]
Oh my bad. It was @DragonHunter274 that is on Arch.

**Comment by cryinkfly** [comment]
@mike-lloyd03: okay you use original system 👍🏻 Can you check if you have the same packages & versions like as by the current manajro version, please?

**Comment by mike-lloyd03** [comment]
I'm not sure what you mean but I just installed this OS last week so all the base stuff should be there. I haven't uninstalled any core packages.

**Comment by cryinkfly** [comment]
It could be that there are differences somewhere. 😅

**Comment by mike-lloyd03** [comment]
I wouldn't know where to look for that.

**Comment by cryinkfly** [comment]
You can check this with pamac (Tool) or with this command: pacman -Q > my_arch_packages.txt

**Comment by mike-lloyd03** [comment]
Oh yeah I know how to see what packages are installed. I just don't know how to compare that with what is normally installed by Manjaro without doing a clean install on another machine and generating the same list and diffing the files.

But like I said, I'm basically running on a clean install. It's only been installed for a week. I have a feeling there's packages that are installed by default on OpenSuse and Ubuntu that aren't installed on Manjaro by default and that's what I'm missing.

**Comment by cryinkfly** [comment]
You are not alone with this problem, when you look to my instructions (Fedora and Ubuntu), then you see it, that on these systems also missing some files.

**Comment by mike-lloyd03** [comment]
Yeah I guess Ubuntu is having the problem as well. But it looks like your OpenSuse system is running great. Perhaps there's something amongst your packages that might be the key?

**Comment by cryinkfly** [comment]
Yes, you are right, but Manjaro works also great. 👍🏻

**Comment by mike-lloyd03** [comment]
Well, here's all my installed packages. Not sure how helpful this will be.

[packages.txt](https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/files/6327930/packages.txt)

**Comment by cryinkfly** [comment]
Okay, I check this for you in the next time. 👍🏻

**Comment by cryinkfly** [comment]
Here you have the file, so that you can compare the packages with your system:

[manjaro-xfce-21.0.1_packages.txt](https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/files/6329178/manjaro-xfce-21.0.1_packages.txt)

... then I have checked Fusion 360 on Manjaro again and it works without any problems. ;-)

**Comment by mike-lloyd03** [comment]
Okay I generated a list of all the packages you have installed that I don't. We're using a different desktop environment (I'm on KDE) so that could be part of it. Do any of these packages stand out to you as possibly being the culprit?

[missing_packages.txt](https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/files/6330617/missing_packages.txt)

**Comment by dreamcat4** [comment]
Hello, I have not looked into the problem yet. But will start today. In the meantimes here is CORRECT winecfg (for ubuntu 20.04, clean install, per Cryinkfly instructions for ubuntu, with the wine 6.6 staging). So if your differs it's something to look at. OK ?

![](https://i.imgur.com/fkOoRqf.png) ![](https://i.imgur.com/cdXFqxI.png)
![](https://i.imgur.com/AyY6ohw.png) ![](https://i.imgur.com/UMYJLCj.png)
![](https://i.imgur.com/aSCvgd4.png)


Will report back later. Once I try some more things out to break it again. If you guys can wait for that....

many thanks

**Comment by dreamcat4** [comment]
ok so here is what i found so far:

when using the system winetricks, this version is installed by the winehq-staging packages from WineHQ repo (on ubuntu). That is wine staging 6.6... it is this version

```sh
[id:~/.bin] $ winetricks.system --version
20200412 - sha256sum: 7651c93e39fcb080483c38836513bf912273a87ea97d137f6b958ed3d9628c3d
```
so with this above ^^ default version of winetricks staging. Then you see the above wine libraries in my previous post here above ^^. And that seems CORRECT and works well. There is NO GLITCHING.


OK so what's the problem? Well some online downloads links for packages  (such as .NET framework etc) can get moved or broken over time. Then the dependancy http:/// link is not found anymore by winetricks. When we try this line:

```sh
winetricks corefonts vcrun2017 msxml4 dxvk
```
it can stops working anytime in the future. since the download links are being hard coded into the winetricks script. So (believe it or not)... the 'official' way to solve this broken download links is to 'update to the latest version of winetricks'. Which is downloaded as a gist.

Therefore I have 2 versions of winetricks on my PATH. There is the system version. Which points to the above WORKING versions from winehq 6.6 staging.. ok. But also there is an 'online' version of winetricks. Which is NEWER. And supposed to be more up to date.

```sh
lrwxrwxrwx 1 id id     22 Apr 18 09:01 winetricks -> winetricks.online.last*
-rwxr-xr-x 1 id id   653K Jan  3  2019 winetricks.old.disabled*
-rwxrwxr-x 1 id id   863K Apr 12 17:10 winetricks.online.last*
lrwxrwxrwx 1 id id     19 Apr 15 12:35 winetricks.system -> /usr/bin/winetricks*
```
with a symlink i point to the version of winetricks to want to use. Here is the latest online version date and shasum:

```sh
θ60° [id:~/.bin] $ winetricks.online.last --version
20210206-next - sha256sum: 346b84b1851021d386dee914d8d997e79c3c15a5ba03b14a754723f8d7223f0c
θ69° [id:~/.bin] $ 
```

To this morning. I had the WORKING fusion 360 installed. It worked. Then the only thing I did was this:

* changed the symlink to point to winetricks
  * WAS: `winetricks.system` = `20200412 - sha256sum: 7651c93e39fcb080483c38836513bf912273a87ea97d137f6b958ed3d9628c3d`
  * NOW: `winetricks.online.last` = `20210206-next - sha256sum: 346b84b1851021d386dee914d8d997e79c3c15a5ba03b14a754723f8d7223f0c`

* then i run:

```sh
winetricks corefonts vcrun2017 msxml4 dxvk
```
only and nothing else. So what happened?

* This happened:

https://gist.github.com/dreamcat4/3f960819e2014915f2e4eec08783dbe4

and it seems from the logs like the newer winetricks version tried to install some extra DLL / winelibs. That were not there before.

* I then: CHANGED NOTHING ELSE

* I then: Re launched Fusion 360 again
  * And the graphics glitches bug appears.

**Comment by dreamcat4** [comment]
So what exactly changed to BREAK the fusion-360 ? Well IDK yet EXACTLY. However it is probably 1+ of these wine libs, see screenshots link here:

https://imgur.com/a/2vgZtkc

Still investigating this issue further

**Comment by cryinkfly** [comment]
@mike-lloyd03 Okay, I have checked Fusion 360 on Manjaro with the KDE destktop enviroment and the program dosn't work.
But I have checked this without a installation!

[manjaro-kde-21.0.1_packages.txt](https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/files/6330792/manjaro-kde-21.0.1_packages.txt)

---

 @dreamcat4 Very good job!!!

It's correct that you don't set these libraries?

> https://imgur.com/a/MsHAkoa

- d3d10core = disabled
- d3d11 = native
- d3d9 = builtin
- dxgi = native

**Comment by dreamcat4** [comment]
correct, i did not set them.

OK so i took the broken install (just now). and compared those 2 lists of wine libs inside the `winecfg`. And the newer winetricks installed a whole bunch of directX or `d*` names for those extra graphics libraries. for directx 9, 10, 11 etc.

So I just deleted all of the names starting with the letter `d*`. And that left me with a list of winelibs that is back to original in the first place.

So the:

```sh
winetricks corefonts vcrun2017 msxml4 dxvk
```

maybe can be without that last one `dxvk` perhaps? IDK if there is any other reason to need it? If we use openGL here instead? Then the line could be (perhaps)

```sh
winetricks corefonts vcrun2017 msxml4
```

Then I relaunch fusion360 (and in opengl graphics mode). And the glitches / flashing is gone. Is OK fixed again.

Hope this helps,

**Comment by cryinkfly** [comment]
The problem at the moment is, that Fusion 360 need some DLL's from the DXVK (winetricks) and so we must check a way, where we can solved this.

**Comment by dreamcat4** [comment]
hello again. indeed you are correct... we need dxvk (winetricks) dlls installed otherwise fusion cannot launch.

however i still cannot fathom why this is happening. still only know as much as from this morning... the winetricks from winehq staging. And also delete all libraries in `winecfg` that start with `d*`. After switching the fusion preferences to `OpenGL` graphics mode

**Comment by cryinkfly** [comment]
@dreamcat4 Ah ... now I know what you mean. I had stated in my instructions that the libraries did not have to be used.
... so I have changed my instructions. 

Sorry ;-)

**Comment by dreamcat4** [comment]
heck you know what? maybe there is a small clue (after all). i think i noticed that after 'disable' all the `d*` graphics libs, then they were not 'removed'. but all 'disabled'. Then fusion would not launch for missing DLL (cannot find them). well one of the missing DLL was something `qt5`....

so it seems like for some reason it needs qt5 to run. And that can be a good clue because other QT5 apps exhibits a similar type of bug on my system. For example 'MEGA Sync' cloud files helper. It does some thing like similar graphics glitches.

So the difference here between your setup and @mike-lloyd03 and myself... it might be something about the QT5 libraries installed for xorg.

sorry i know that sounds pretty ridiculous. but maybe there is a reason since in fact Fusion360 does use QT5 on windows, it needs some `qt5*.dll`. This is true.

So between QT5 and dxvk something is going on IDK

i then read this comment:

https://github.com/doitsujin/dxvk/issues/1388#issuecomment-580713250

so maybe it's worth to try installing dxvk without dxgi.

```sh
dxvk-1.8.1/setup_dxvk.sh --help
Unrecognized action: --help
Usage: ./setup_dxvk.sh [install|uninstall] [--without-dxgi] [--with-d3d10] [--symlink]
```

or otherwise remove only the `dxgi` from winecfg.

... but also look into QT5 issue. maybe something there too

```sh
$ env | grep -i qt_
QT_ACCESSIBILITY=1
QT_QPA_PLATFORMTHEME=qt5ct
QT_IM_MODULE=ibus
```

IDK. it's just a hunch really at this point

**Comment by mike-lloyd03** [comment]
Okay I generated a list of all the packages you have installed that I don't. We're using a different desktop environment (I'm on KDE) so that could be part of it. Do any of these packages stand out to you as possibly being the culprit?

[missing_packages.txt](https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/files/6332337/missing_packages.txt)

**Comment by mike-lloyd03** [comment]
KDE is built with QT5 so I should have any requisite QT5 libraries installed.

**Comment by cryinkfly** [comment]
@dreamcat4 

> doitsujin/dxvk#1388 (comment)

... very interesting. 👍



@mike-lloyd03 

> KDE is built with QT5 so I should have any requisite QT5 libraries installed

Could it also be that something else is configured somewhere with you than with Manjaro that is the case?

**Comment by dreamcat4** [comment]
err.. what i was saying is because fusion360 loads certain graphics dlls for the gui, you can see them if you scrolls down from here

https://doc.qt.io/qt-5/windows-deployment.html#linking-the-application-to-qt-as-a-shared-library

and because the qt5 project has something huge like 3000 open bugs on its issues tracker. and is known for graphics glitching like we have been seeing. so maybe a complicated rendering bug in qt is making the opengl calls. and opengl is simply just doing what its told to do...

and then this bug is not seen by the fusion 360 developers on natuve windows platform. only when running in wine linux

i do also see similar graphics issue in other native linux qt5 applications. on my same computer. they are not exactly the same issue, but similar ways the rendering is not updating properly

**Comment by dreamcat4** [comment]
quick question - do you have multiple monitors @mike-lloyd03 ? do you have an nvidia gaphics card? just curious as i do have that setup here myself. but i don't think it's the issue! ...because after unplugging the 2nd monitor, and relaunching fusion with only 1 monitor. then bug still appears just the same. just wanted to rule that one out as a possibility

**Comment by dreamcat4** [comment]
@cryinkfly can you please run the following 2 simple commands in four ubuntu 20.04 wineprefix? Or perhaps you don't have it anymore. then in your current fusion360 install (on other distro)

```sh
winetricks --version
winetricks list-installed
```
thanks

**Comment by dreamcat4** [comment]
A good day today!

ok @cryinkfly i have been experimenting some more, and now is found the 'best current known solution' for avoiding this bug. So can you update your instructions, please for this is minor change! But it really helps.  Here in the following step

Replace this step:

```sh
19.) Run this command: winecfg -> Go to libraries -> Change these options:

d3d10core = disabled
d3d11 = native
d3d9 = builtin
dxgi = native
```

With this new instruction:

```sh
19.) Run this command: winecfg -> Go to libraries -> Change these options:
d3d11 = builtin

+ADD BRIEF EXPLANATORY TEXT HERE, SEE BELOW vv VERBOSE COMMENTS
```

so what does this do? Well it appears to override the `d3d11.dll` from the microsoft windows version --> to the dxvk version. This will then ensure that the flashing / glitching (witch the background, or the splash screen). will not happen anymore.

BUT ALSO: when i changed this 1 thing, it also fixed the other issue. Where the 'Brower' floating menus kept appearing above all other windows. So that graphics glitch is gone too.

For the other 3 dlls in your list here... i do know know what is the point. so i did not change any other ones. at least for OpenGL graphics mode. which is what we are using now. So i think maybe don't include them anymore. they just seem for dx9 / dx10 stuff only.  which we don't use.

HOWEVER maybe it's a nice 'experiment' to see what happens in fusion360 dx9, or dx10 or dx11 modes, to change them all to dxvk (vulkan) by setting override = BUILTIN. on all of them. and then see with the latest dxvk version 181 what happens. If it's still worse than OpenGL mode.

I think this is a well considered recommendation here. And not to need to worry too much else (for this graphics bug). However I shall continue testing today, from the beginning again. To double check there is indeed fixed properly. So if i find anything else will report back.

BTW #1

by clicking "REMOVE" button on the d3d11 in the winecfg libraries dlls list. it does also solve the main graphics flashing glitches problem. for this bug we raised. HOWEVER it does not also fix the floating Browser menu always ontop. If you understand that? Because those are some QT5 gui widgets / gui elements, thats being rendered by QT... which still has other weird bugs in it. when combined with the graphics calls it sends to lower layers. SO this is why the new recommendation is not to 'remove'. But instead to change to 'BUILTIN' = dxvk dll override instead. And hope that the future vulkan dxvk releases after 181 does not break anything new. Since fusion is also updated too in future ;)


BTW #2 here was the smoking gun i eventually saw, using this command `ps -aux | grep -i qt`... because it showed up these running background processes. you can see in the program arguments, that fusion developers are spawning this task with the compatibility flag `AdCefWebBrowser.exe --disable-d3d11`


```sh
[id:~/Games/autodesk-fusion-360] $ ps -aux | grep -i "autodesk"
id        428049  0.0  0.1 2016264 70916 ?       Sl   09:45   0:02 C:/Program Files/Autodesk/webdeploy/production/5873edb3ce0a7ce93d3ee911f7ba68d35a7e5862/adexmtsv.exe C:/ProgramData/Autodesk/Common/Material Library/20081401/adexmtsv_prod.cfg -p /tmp/20081401id
id        428145  0.0  0.1 2027692 68900 ?       Sl   09:45   0:00 C:\users\id\Application Data\Autodesk\ADPSDK\bin\ADPClientService.exe -f C:\users\id\Application Data\Autodesk\ADPSDK\JSON
id        429215  0.0  0.2 3880444 182692 ?      Sl   09:45   0:03 C:/Program Files/Autodesk/webdeploy/production/5873edb3ce0a7ce93d3ee911f7ba68d35a7e5862/Win64/AdCefWebBrowser.exe --disable-d3d11 --log-severity=disabled --lang=en -remote-debugging-port=1234 --product-version=Neutron/2.0.10032 --no-proxy-server --cache-path=C:/users/id/Temp/Autodesk/BrowserCache/2.0.10032
id        429999  0.1  0.3 2651100 244404 ?      Sl   09:46   0:06 C:\Program Files\Autodesk\webdeploy\production\5873edb3ce0a7ce93d3ee911f7ba68d35a7e5862\Win64\AdCefWebBrowser.exe --type=gpu-process --no-sandbox --disable-d3d11 --lang=en --log-file=C:/users/id/Temp/Autodesk/BrowserCache/2.0.10032\debug.log --log-severity=disable --product-version=Neutron/2.0.10032 Chrome/59.0.3071 --supports-dual-gpus=false --gpu-driver-bug-workarounds=7,10,20,21,24,43,76 --disable-gl-extensions=GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent --gpu-vendor-id=0x10de --gpu-device-id=0x1d01 --gpu-driver-vendor --gpu-driver-version --gpu-driver-date=4-22-2021 --lang=en --log-file=C:/users/id/Temp/Autodesk/BrowserCache/2.0.10032\debug.log --log-severity=disable --product-version=Neutron/2.0.10032 Chrome/59.0.3071 --service-request-channel-token=D1CC0E641E5B0FDCD18F7DA1AD6A48E4 --mojo-platform-channel-handle=776 /prefetch:2
id        430071  0.0  0.3 7679512 205808 ?      Ssl  09:46   0:02 C:\Program Files\Autodesk\webdeploy\production\5873edb3ce0a7ce93d3ee911f7ba68d35a7e5862\QtWebEngineProcess.exe --type=renderer --disable-speech-api --enable-threaded-compositing --enable-features=AllowContentInitiatedDataUrlNavigations,TracingServiceInProcess --disable-features=BackgroundFetch,ConsolidatedMovementXY,DnsOverHttpsUpgrade,FormControlsRefresh,MojoVideoCapture,PictureInPicture,SmsReceiver,UseSkiaRenderer,WebPayments,WebUSB --disable-databases --lang=en-US --webengine-schemes=qrc:sLV --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=4 --mojo-platform-channel-handle=5300 /prefetch:1
id        430107  0.0  0.2 7657104 195536 ?      Ssl  09:46   0:00 C:\Program Files\Autodesk\webdeploy\production\5873edb3ce0a7ce93d3ee911f7ba68d35a7e5862\QtWebEngineProcess.exe --type=renderer --disable-speech-api --enable-threaded-compositing --enable-features=AllowContentInitiatedDataUrlNavigations,TracingServiceInProcess --disable-features=BackgroundFetch,ConsolidatedMovementXY,DnsOverHttpsUpgrade,FormControlsRefresh,MojoVideoCapture,PictureInPicture,SmsReceiver,UseSkiaRenderer,WebPayments,WebUSB --disable-databases --lang=en-US --webengine-schemes=qrc:sLV --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=5 --mojo-platform-channel-handle=5612 /prefetch:1
id        430694  0.0  0.2 7660308 191792 ?      Ssl  09:46   0:00 C:\Program Files\Autodesk\webdeploy\production\5873edb3ce0a7ce93d3ee911f7ba68d35a7e5862\QtWebEngineProcess.exe --type=renderer --disable-speech-api --enable-threaded-compositing --enable-features=AllowContentInitiatedDataUrlNavigations,TracingServiceInProcess --disable-features=BackgroundFetch,ConsolidatedMovementXY,DnsOverHttpsUpgrade,FormControlsRefresh,MojoVideoCapture,PictureInPicture,SmsReceiver,UseSkiaRenderer,WebPayments,WebUSB --disable-databases --lang=en-US --webengine-schemes=qrc:sLV --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=8 --mojo-platform-channel-handle=7516 /prefetch:1
id        438881  0.0  0.0 1950612 64196 ?       Sl   09:51   0:01 C:/Program Files/Autodesk/webdeploy/production/5873edb3ce0a7ce93d3ee911f7ba68d35a7e5862/adexmtsv.exe C:/ProgramData/Autodesk/Common/Material Library/20081401/adexmtsv_prod.cfg -p /tmp/20081401id
id        498593  0.0  0.0 1950612 64504 ?       Sl   10:27   0:01 C:/Program Files/Autodesk/webdeploy/production/5873edb3ce0a7ce93d3ee911f7ba68d35a7e5862/adexmtsv.exe C:/ProgramData/Autodesk/Common/Material Library/20081401/adexmtsv_prod.cfg -p /tmp/20081401id
id        501487  0.0  0.1 2016200 70708 ?       Sl   10:29   0:02 C:/Program Files/Autodesk/webdeploy/production/5873edb3ce0a7ce93d3ee911f7ba68d35a7e5862/adexmtsv.exe C:/ProgramData/Autodesk/Common/Material Library/20081401/adexmtsv_prod.cfg -p /tmp/20081401id
id        501636  0.0  0.0 1909128 39616 ?       Sl   10:29   0:00 C:\users\id\Application Data\Autodesk\ADPSDK\bin\ADPClientService.exe -f C:\users\id\Application Data\Autodesk\ADPSDK\JSON
id        502298  0.0  0.2 3947632 189128 ?      Sl   10:29   0:02 C:/Program Files/Autodesk/webdeploy/production/5873edb3ce0a7ce93d3ee911f7ba68d35a7e5862/Win64/AdCefWebBrowser.exe --disable-d3d11 --log-severity=disabled --lang=en -remote-debugging-port=1234 --product-version=Neutron/2.0.10032 --no-proxy-server --cache-path=C:/users/id/Temp/Autodesk/BrowserCache/2.0.10032
id        502921  0.0  0.3 7659916 206552 ?      Ssl  10:29   0:01 C:\Program Files\Autodesk\webdeploy\production\5873edb3ce0a7ce93d3ee911f7ba68d35a7e5862\QtWebEngineProcess.exe --type=renderer --disable-speech-api --enable-threaded-compositing --enable-features=AllowContentInitiatedDataUrlNavigations,TracingServiceInProcess --disable-features=BackgroundFetch,ConsolidatedMovementXY,DnsOverHttpsUpgrade,FormControlsRefresh,MojoVideoCapture,PictureInPicture,SmsReceiver,UseSkiaRenderer,WebPayments,WebUSB --disable-databases --lang=en-US --webengine-schemes=qrc:sLV --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=4 --mojo-platform-channel-handle=5496 /prefetch:1
id        502959  0.0  0.3 7656712 206704 ?      Ssl  10:29   0:00 C:\Program Files\Autodesk\webdeploy\production\5873edb3ce0a7ce93d3ee911f7ba68d35a7e5862\QtWebEngineProcess.exe --type=renderer --disable-speech-api --enable-threaded-compositing --enable-features=AllowContentInitiatedDataUrlNavigations,TracingServiceInProcess --disable-features=BackgroundFetch,ConsolidatedMovementXY,DnsOverHttpsUpgrade,FormControlsRefresh,MojoVideoCapture,PictureInPicture,SmsReceiver,UseSkiaRenderer,WebPayments,WebUSB --disable-databases --lang=en-US --webengine-schemes=qrc:sLV --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=5 --mojo-platform-channel-handle=5840 /prefetch:1
id        504100  0.0  0.3 7660940 199556 ?      Ssl  10:30   0:00 C:\Program Files\Autodesk\webdeploy\production\5873edb3ce0a7ce93d3ee911f7ba68d35a7e5862\QtWebEngineProcess.exe --type=renderer --disable-speech-api --enable-threaded-compositing --enable-features=AllowContentInitiatedDataUrlNavigations,TracingServiceInProcess --disable-features=BackgroundFetch,ConsolidatedMovementXY,DnsOverHttpsUpgrade,FormControlsRefresh,MojoVideoCapture,PictureInPicture,SmsReceiver,UseSkiaRenderer,WebPayments,WebUSB --disable-databases --lang=en-US --webengine-schemes=qrc:sLV --device-scale-factor=1 --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=8 --mojo-platform-channel-handle=5100 /prefetch:1
id        618409  0.0  0.0   9044  2708 pts/2    S+   11:27   0:00 grep --color=auto -i autodesk
```

all fun and games...

Hope it helps. For this new advice. Many thanks for doing these installation guides. Really it helped my a lot. Also it gave me a lot more confidence now to know about dxvk. Like what it is... and also maybe to try out testing WINE for other windows applications. Such as (for example) rhino 3d. Or alibre cad. Because those competing CAD programs use far less resources. And should be much faster / more efficient. Than all the https web requests bloat of fusion360. That does not happen in the other programs.

**Comment by mike-lloyd03** [comment]
> quick question - do you have multiple monitors @mike-lloyd03 ? do you have an nvidia gaphics card?

I do have an nvidia graphics card but only one monitor (built in laptop monitor).

**Comment by dreamcat4** [comment]
ok thanks it doesnt matter. see my previous last comment here for the solution

https://github.com/cryinkfly/Fusion-360---Linux-Wine-Version-/issues/6#issuecomment-824775900

**Comment by cryinkfly** [comment]
Sorry for barely reporting back the days.

@dreamcat4 I changed the library's on my system (openSUSE Leap 15.3), but it doesn't work.

https://user-images.githubusercontent.com/79079633/115723279-18ac0480-a380-11eb-9182-f869d52bed95.mov


---

> winetricks --version
winetricks list-installed

Winetricks version: 20210206
winetricks list-installed:

- andale
- arial
- comicsans
- courier
- georgia
- impact
- times
- trebuchet
- verdana
- webdings
- corefonts
- w_workaround_wine_bug-37781
- vcrun2017
- msxml4
- w_workaround_wine_bug-24013
- d3dcompiler_43
- d3dx9
- dxvk

---


> quick question - do you have multiple monitors @mike-lloyd03 ? do you have an nvidia gaphics card? just curious as i do have that setup here myself. but i don't think it's the issue! ...because after unplugging the 2nd monitor, and relaunching fusion with only 1 monitor. then bug still appears just the same. just wanted to rule that one out as a possibility

I use sometimes my second monitor and so I can tell, that Fusion 360 works also, when you use two monitors.

**Comment by cryinkfly** [comment]
@dreamcat4 

> BTW 2
here was the smoking gun i eventually saw, using this command ps -aux | grep -i qt... because it showed up these running background processes. you can see in the program arguments, that fusion developers are spawning this task with the compatibility flag **AdCefWebBrowser.exe --disable-d3d11**

![#1 1_AdCefWebBrowser_disable](https://user-images.githubusercontent.com/79079633/115730709-d33f0580-a386-11eb-905b-d46535475ad2.png)
![#1 2_AdCefWebBrowser_disable](https://user-images.githubusercontent.com/79079633/115730715-d4703280-a386-11eb-82b6-44eda189fd06.png)
![#1 3_AdCefWebBrowser_disable](https://user-images.githubusercontent.com/79079633/115730722-d5a15f80-a386-11eb-98d5-c0bb4b4e4571.png)
![#1 4_AdCefWebBrowser_disable](https://user-images.githubusercontent.com/79079633/115730724-d639f600-a386-11eb-8258-e35acc93df55.png)
![#1 5_AdCefWebBrowser_disable](https://user-images.githubusercontent.com/79079633/115730729-d6d28c80-a386-11eb-9b6b-489760ff4328.png)
![#1 6_AdCefWebBrowser_disable](https://user-images.githubusercontent.com/79079633/115730733-d76b2300-a386-11eb-985f-9da3a8244987.png)
![#1 7_AdCefWebBrowser_disable](https://user-images.githubusercontent.com/79079633/115730742-d89c5000-a386-11eb-962a-4afb9b161ddf.png)


---


... I have tested this and I can tell you, when you use this, then Fusion 360 starts very quickly into the workspace, but with this configuration we get some problems:

![#1 8_AdCefWebBrowser_disable](https://user-images.githubusercontent.com/79079633/115732417-409f6600-a388-11eb-8766-433659a55ee1.png)

**Comment by dreamcat4** [comment]
ok thanks. It seems that when you set 'disable' on dlls... it does in fact only partially disable the dll. What happens is that the dll cannot be loaded anymore when the program starts up. However for some weird reason (or bug whatever). The 'disabled' dll is still 'detected' or noticed by fusion360. So this is a problem you will see in the terminal... fusion log will say `err: something dll not found`.

But if you were to `delete` the dll with the `remove` button. Then it is not detectable anymore by fusion360. When the program loads. Sorry I do not know the proper solution for this problem. But should be the reason why you getting the launch error in the background task for the web browser there.


I have tried not on a clean install, and can also see your point about the dxgi.dll. It also needs to be changed to `builtin`. Otherwise fusion360 cannot load. I saw that same error message. The reason i didn't notice on first success was because... i had already deleted the dxgi.dll with remove button. For same reason above ^^. hehe. And also the other thing broken is right click context menu now. Which is just so random.

So yes this still needs some more work. I will try again from the beginning.

**Comment by cryinkfly** [comment]
### I have found this:

**If you use Wine under XWayland, you can activate the option for "Emulating a virtual desktop" in the Graphics Tab in winecfg, to avoid problems with:**

    flickering
    wrong window location
    wrong mouse cursor location and clicks
    keyboard detection

**Comment by dreamcat4** [comment]
how do you use wayland with nvidia GPU ? is that with the noveau drivers? or because of intel IGP / optimus on your laptop? Because with my system the wayland option has been disabled now. For me with proprietary nvidia graphics driver

**Comment by cryinkfly** [comment]
No no .... ^^ I don't use wayland ;D

**Comment by mike-lloyd03** [comment]
@dreamcat4 you steely eyed wine man! I changed d3d11 and dxgi to builtin and it works! Pretty smooth as well! I'm still getting the floating menus across all my virtual desktops however.

I wasn't sure what to do with the other DirectX libraries so this is what I currently have set:
```
d3d10core = disabled
d3d11 = builtin
d3d9 = builtin
dxgi = builtin
```

Is this right?

**Comment by cryinkfly** [comment]
@mike-lloyd03 Yes, your configuration is right. :-)

### Update: I have changed my manual!

**Comment by dreamcat4** [comment]
> still getting the floating menus across all my virtual desktops however.

if you set the Watch notifications button here to "All activity", then you will be notified for new issues. Because we have opened some seperate issue for that bug now. You can see the discussion over on the other issue page. Many thanks
